### PR TITLE
Added the ability to specify a branch

### PR DESCRIPTION
**Pull request by Davilink**

### CODE REVIEW

**Comment by jlandersen** [comment]
Hi, thanks for the PR!

I will check it within the next few days and make sure it gets released next week

**Comment by Davilink** [comment]
Great !

**Review by jlandersen — CHANGES_REQUESTED** [review]
Overall looks good. Minor change before merging - "Branch (left empty to use the default branch) ?" should be "Branch (leave empty to use default) ?"

**Comment by Davilink** [comment]
Done !

**Comment by jlandersen** [comment]
Cool, thanks alot!

**Comment by jlandersen** [comment]
0.6.0 is live with the changes

**Pull request merged**
